### ISSUE TITLE
Ebola IMC Dataset

### ISSUE THREAD

**Issue by Rajratnpranesh** [broadinstitute/ebola-imc-code#1]
"Machine-learning Prognostic Models from the 2014–16 Ebola Outbreak "is great work. While exploring this repro I could not find the exact dataset used in the paper. 
It would be highly appreciable if you guys can put a link or upload the Ebola IMC dataset. It would be very useful for me in taking the research work further.
Thank you.

**Comment by codeanticode** [comment]
Apologies for the very slow response. The data used in this analysis is now available through [IDDO's Ebola Data Platform](https://www.iddo.org/research-themes/ebola).
